# Generated by Django 5.2.5 on 2025-09-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria_nome", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=200)),
                (
                    "categoria_imagem",
                    models.ImageField(blank=True, upload_to="fotos/categorias"),
                ),
            ],
        ),
    ]
