# Generated by Django 5.2.5 on 2025-09-10 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categoria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto_nome", models.CharField(max_length=200, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=300)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=11)),
                ("estoque", models.IntegerField()),
                ("imagem", models.ImageField(blank=True, upload_to="fotos/produtos")),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("esta_disponivel", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("modificado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categoria.categoria",
                    ),
                ),
            ],
        ),
    ]
